---
language: python
python:
  - "2.7"
  - "3.6"

services:
  - docker

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-grafana-annotations-bot grafana-annotations-bot
  - cd grafana-annotations-bot

script:
  - molecule --version
  - ansible --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/